//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteForms.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    //using Biblioteca.pacoteSala;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InserirClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirArtistaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarArtistaOperationCompleted;

        /*internal void InserirSala(Biblioteca.pacoteSala.Sala sala)
        {
            throw new NotImplementedException();
        }*/

        private System.Threading.SendOrPostCallback AlterarArtistaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarArtistaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirSalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarSalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarSalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarSalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirHorarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarHorarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarHorarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarHorarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirInstrumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarInstrumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarInstrumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarInstrumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirLocacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarLocacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarLocacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarLocacaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ClienteForms.Properties.Settings.Default.ClienteForms_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InserirClienteCompletedEventHandler InserirClienteCompleted;
        
        /// <remarks/>
        public event DeletarClienteCompletedEventHandler DeletarClienteCompleted;
        
        /// <remarks/>
        public event AlterarClienteCompletedEventHandler AlterarClienteCompleted;
        
        /// <remarks/>
        public event ListarClienteCompletedEventHandler ListarClienteCompleted;
        
        /// <remarks/>
        public event InserirArtistaCompletedEventHandler InserirArtistaCompleted;
        
        /// <remarks/>
        public event DeletarArtistaCompletedEventHandler DeletarArtistaCompleted;
        
        /// <remarks/>
        public event AlterarArtistaCompletedEventHandler AlterarArtistaCompleted;
        
        /// <remarks/>
        public event ListarArtistaCompletedEventHandler ListarArtistaCompleted;
        
        /// <remarks/>
        public event InserirSalaCompletedEventHandler InserirSalaCompleted;
        
        /// <remarks/>
        public event DeletarSalaCompletedEventHandler DeletarSalaCompleted;
        
        /// <remarks/>
        public event AlterarSalaCompletedEventHandler AlterarSalaCompleted;
        
        /// <remarks/>
        public event ListarSalaCompletedEventHandler ListarSalaCompleted;
        
        /// <remarks/>
        public event InserirHorarioCompletedEventHandler InserirHorarioCompleted;
        
        /// <remarks/>
        public event DeletarHorarioCompletedEventHandler DeletarHorarioCompleted;
        
        /// <remarks/>
        public event AlterarHorarioCompletedEventHandler AlterarHorarioCompleted;
        
        /// <remarks/>
        public event ListarHorarioCompletedEventHandler ListarHorarioCompleted;
        
        /// <remarks/>
        public event InserirInstrumentoCompletedEventHandler InserirInstrumentoCompleted;
        
        /// <remarks/>
        public event DeletarInstrumentoCompletedEventHandler DeletarInstrumentoCompleted;
        
        /// <remarks/>
        public event AlterarInstrumentoCompletedEventHandler AlterarInstrumentoCompleted;
        
        /// <remarks/>
        public event ListarInstrumentoCompletedEventHandler ListarInstrumentoCompleted;
        
        /// <remarks/>
        public event InserirTipoCompletedEventHandler InserirTipoCompleted;
        
        /// <remarks/>
        public event DeletarTipoCompletedEventHandler DeletarTipoCompleted;
        
        /// <remarks/>
        public event AlterarTipoCompletedEventHandler AlterarTipoCompleted;
        
        /// <remarks/>
        public event ListarTipoCompletedEventHandler ListarTipoCompleted;
        
        /// <remarks/>
        public event InserirLocacaoCompletedEventHandler InserirLocacaoCompleted;
        
        /// <remarks/>
        public event CancelarLocacaoCompletedEventHandler CancelarLocacaoCompleted;
        
        /// <remarks/>
        public event AlterarLocacaoCompletedEventHandler AlterarLocacaoCompleted;
        
        /// <remarks/>
        public event ListarLocacaoCompletedEventHandler ListarLocacaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente cliente) {
            this.Invoke("InserirCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void InserirClienteAsync(Cliente cliente) {
            this.InserirClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void InserirClienteAsync(Cliente cliente, object userState) {
            if ((this.InserirClienteOperationCompleted == null)) {
                this.InserirClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirClienteOperationCompleted);
            }
            this.InvokeAsync("InserirCliente", new object[] {
                        cliente}, this.InserirClienteOperationCompleted, userState);
        }
        
        private void OnInserirClienteOperationCompleted(object arg) {
            if ((this.InserirClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente cliente) {
            this.Invoke("DeletarCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void DeletarClienteAsync(Cliente cliente) {
            this.DeletarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void DeletarClienteAsync(Cliente cliente, object userState) {
            if ((this.DeletarClienteOperationCompleted == null)) {
                this.DeletarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarClienteOperationCompleted);
            }
            this.InvokeAsync("DeletarCliente", new object[] {
                        cliente}, this.DeletarClienteOperationCompleted, userState);
        }
        
        private void OnDeletarClienteOperationCompleted(object arg) {
            if ((this.DeletarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente cliente) {
            this.Invoke("AlterarCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void AlterarClienteAsync(Cliente cliente) {
            this.AlterarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void AlterarClienteAsync(Cliente cliente, object userState) {
            if ((this.AlterarClienteOperationCompleted == null)) {
                this.AlterarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarClienteOperationCompleted);
            }
            this.InvokeAsync("AlterarCliente", new object[] {
                        cliente}, this.AlterarClienteOperationCompleted, userState);
        }
        
        private void OnAlterarClienteOperationCompleted(object arg) {
            if ((this.AlterarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteCliente")]
        public Cliente[] ListarCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente cliente) {
            object[] results = this.Invoke("ListarCliente", new object[] {
                        cliente});
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClienteAsync(Cliente cliente) {
            this.ListarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void ListarClienteAsync(Cliente cliente, object userState) {
            if ((this.ListarClienteOperationCompleted == null)) {
                this.ListarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClienteOperationCompleted);
            }
            this.InvokeAsync("ListarCliente", new object[] {
                        cliente}, this.ListarClienteOperationCompleted, userState);
        }
        
        private void OnListarClienteOperationCompleted(object arg) {
            if ((this.ListarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClienteCompleted(this, new ListarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirArtista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirArtista([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Artista artista) {
            this.Invoke("InserirArtista", new object[] {
                        artista});
        }
        
        /// <remarks/>
        public void InserirArtistaAsync(Artista artista) {
            this.InserirArtistaAsync(artista, null);
        }
        
        /// <remarks/>
        public void InserirArtistaAsync(Artista artista, object userState) {
            if ((this.InserirArtistaOperationCompleted == null)) {
                this.InserirArtistaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirArtistaOperationCompleted);
            }
            this.InvokeAsync("InserirArtista", new object[] {
                        artista}, this.InserirArtistaOperationCompleted, userState);
        }
        
        private void OnInserirArtistaOperationCompleted(object arg) {
            if ((this.InserirArtistaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirArtistaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarArtista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarArtista([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Artista artista) {
            this.Invoke("DeletarArtista", new object[] {
                        artista});
        }
        
        /// <remarks/>
        public void DeletarArtistaAsync(Artista artista) {
            this.DeletarArtistaAsync(artista, null);
        }
        
        /// <remarks/>
        public void DeletarArtistaAsync(Artista artista, object userState) {
            if ((this.DeletarArtistaOperationCompleted == null)) {
                this.DeletarArtistaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarArtistaOperationCompleted);
            }
            this.InvokeAsync("DeletarArtista", new object[] {
                        artista}, this.DeletarArtistaOperationCompleted, userState);
        }
        
        private void OnDeletarArtistaOperationCompleted(object arg) {
            if ((this.DeletarArtistaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarArtistaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarArtista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarArtista([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Artista artista) {
            this.Invoke("AlterarArtista", new object[] {
                        artista});
        }
        
        /// <remarks/>
        public void AlterarArtistaAsync(Artista artista) {
            this.AlterarArtistaAsync(artista, null);
        }
        
        /// <remarks/>
        public void AlterarArtistaAsync(Artista artista, object userState) {
            if ((this.AlterarArtistaOperationCompleted == null)) {
                this.AlterarArtistaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarArtistaOperationCompleted);
            }
            this.InvokeAsync("AlterarArtista", new object[] {
                        artista}, this.AlterarArtistaOperationCompleted, userState);
        }
        
        private void OnAlterarArtistaOperationCompleted(object arg) {
            if ((this.AlterarArtistaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarArtistaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarArtista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteArtista")]
        public Artista[] ListarArtista([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Artista filtro) {
            object[] results = this.Invoke("ListarArtista", new object[] {
                        filtro});
            return ((Artista[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarArtistaAsync(Artista filtro) {
            this.ListarArtistaAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarArtistaAsync(Artista filtro, object userState) {
            if ((this.ListarArtistaOperationCompleted == null)) {
                this.ListarArtistaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarArtistaOperationCompleted);
            }
            this.InvokeAsync("ListarArtista", new object[] {
                        filtro}, this.ListarArtistaOperationCompleted, userState);
        }
        
        private void OnListarArtistaOperationCompleted(object arg) {
            if ((this.ListarArtistaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarArtistaCompleted(this, new ListarArtistaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirSala", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirSala([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Sala sala) {
            this.Invoke("InserirSala", new object[] {
                        sala});
        }
        
        /// <remarks/>
        public void InserirSalaAsync(Sala sala) {
            this.InserirSalaAsync(sala, null);
        }
        
        /// <remarks/>
        public void InserirSalaAsync(Sala sala, object userState) {
            if ((this.InserirSalaOperationCompleted == null)) {
                this.InserirSalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirSalaOperationCompleted);
            }
            this.InvokeAsync("InserirSala", new object[] {
                        sala}, this.InserirSalaOperationCompleted, userState);
        }
        
        private void OnInserirSalaOperationCompleted(object arg) {
            if ((this.InserirSalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirSalaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarSala", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarSala([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Sala sala) {
            this.Invoke("DeletarSala", new object[] {
                        sala});
        }
        
        /// <remarks/>
        public void DeletarSalaAsync(Sala sala) {
            this.DeletarSalaAsync(sala, null);
        }
        
        /// <remarks/>
        public void DeletarSalaAsync(Sala sala, object userState) {
            if ((this.DeletarSalaOperationCompleted == null)) {
                this.DeletarSalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarSalaOperationCompleted);
            }
            this.InvokeAsync("DeletarSala", new object[] {
                        sala}, this.DeletarSalaOperationCompleted, userState);
        }
        
        private void OnDeletarSalaOperationCompleted(object arg) {
            if ((this.DeletarSalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarSalaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarSala", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarSala([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Sala sala) {
            this.Invoke("AlterarSala", new object[] {
                        sala});
        }
        
        /// <remarks/>
        public void AlterarSalaAsync(Sala sala) {
            this.AlterarSalaAsync(sala, null);
        }
        
        /// <remarks/>
        public void AlterarSalaAsync(Sala sala, object userState) {
            if ((this.AlterarSalaOperationCompleted == null)) {
                this.AlterarSalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarSalaOperationCompleted);
            }
            this.InvokeAsync("AlterarSala", new object[] {
                        sala}, this.AlterarSalaOperationCompleted, userState);
        }
        
        private void OnAlterarSalaOperationCompleted(object arg) {
            if ((this.AlterarSalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarSalaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarSala", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteSala")]
        public Sala[] ListarSala([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Sala filtro) {
            object[] results = this.Invoke("ListarSala", new object[] {
                        filtro});
            return ((Sala[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarSalaAsync(Sala filtro) {
            this.ListarSalaAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarSalaAsync(Sala filtro, object userState) {
            if ((this.ListarSalaOperationCompleted == null)) {
                this.ListarSalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSalaOperationCompleted);
            }
            this.InvokeAsync("ListarSala", new object[] {
                        filtro}, this.ListarSalaOperationCompleted, userState);
        }
        
        private void OnListarSalaOperationCompleted(object arg) {
            if ((this.ListarSalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSalaCompleted(this, new ListarSalaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirHorario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirHorario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Horario horario) {
            this.Invoke("InserirHorario", new object[] {
                        horario});
        }
        
        /// <remarks/>
        public void InserirHorarioAsync(Horario horario) {
            this.InserirHorarioAsync(horario, null);
        }
        
        /// <remarks/>
        public void InserirHorarioAsync(Horario horario, object userState) {
            if ((this.InserirHorarioOperationCompleted == null)) {
                this.InserirHorarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirHorarioOperationCompleted);
            }
            this.InvokeAsync("InserirHorario", new object[] {
                        horario}, this.InserirHorarioOperationCompleted, userState);
        }
        
        private void OnInserirHorarioOperationCompleted(object arg) {
            if ((this.InserirHorarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirHorarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarHorario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarHorario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Horario horario) {
            this.Invoke("DeletarHorario", new object[] {
                        horario});
        }
        
        /// <remarks/>
        public void DeletarHorarioAsync(Horario horario) {
            this.DeletarHorarioAsync(horario, null);
        }
        
        /// <remarks/>
        public void DeletarHorarioAsync(Horario horario, object userState) {
            if ((this.DeletarHorarioOperationCompleted == null)) {
                this.DeletarHorarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarHorarioOperationCompleted);
            }
            this.InvokeAsync("DeletarHorario", new object[] {
                        horario}, this.DeletarHorarioOperationCompleted, userState);
        }
        
        private void OnDeletarHorarioOperationCompleted(object arg) {
            if ((this.DeletarHorarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarHorarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarHorario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarHorario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Horario horario) {
            this.Invoke("AlterarHorario", new object[] {
                        horario});
        }
        
        /// <remarks/>
        public void AlterarHorarioAsync(Horario horario) {
            this.AlterarHorarioAsync(horario, null);
        }
        
        /// <remarks/>
        public void AlterarHorarioAsync(Horario horario, object userState) {
            if ((this.AlterarHorarioOperationCompleted == null)) {
                this.AlterarHorarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarHorarioOperationCompleted);
            }
            this.InvokeAsync("AlterarHorario", new object[] {
                        horario}, this.AlterarHorarioOperationCompleted, userState);
        }
        
        private void OnAlterarHorarioOperationCompleted(object arg) {
            if ((this.AlterarHorarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarHorarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarHorario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteHorario")]
        public Horario[] ListarHorario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Horario horario) {
            object[] results = this.Invoke("ListarHorario", new object[] {
                        horario});
            return ((Horario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarHorarioAsync(Horario horario) {
            this.ListarHorarioAsync(horario, null);
        }
        
        /// <remarks/>
        public void ListarHorarioAsync(Horario horario, object userState) {
            if ((this.ListarHorarioOperationCompleted == null)) {
                this.ListarHorarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarHorarioOperationCompleted);
            }
            this.InvokeAsync("ListarHorario", new object[] {
                        horario}, this.ListarHorarioOperationCompleted, userState);
        }
        
        private void OnListarHorarioOperationCompleted(object arg) {
            if ((this.ListarHorarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarHorarioCompleted(this, new ListarHorarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirInstrumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirInstrumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Instrumento instrumento) {
            this.Invoke("InserirInstrumento", new object[] {
                        instrumento});
        }
        
        /// <remarks/>
        public void InserirInstrumentoAsync(Instrumento instrumento) {
            this.InserirInstrumentoAsync(instrumento, null);
        }
        
        /// <remarks/>
        public void InserirInstrumentoAsync(Instrumento instrumento, object userState) {
            if ((this.InserirInstrumentoOperationCompleted == null)) {
                this.InserirInstrumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirInstrumentoOperationCompleted);
            }
            this.InvokeAsync("InserirInstrumento", new object[] {
                        instrumento}, this.InserirInstrumentoOperationCompleted, userState);
        }
        
        private void OnInserirInstrumentoOperationCompleted(object arg) {
            if ((this.InserirInstrumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirInstrumentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarInstrumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarInstrumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Instrumento instrumento) {
            this.Invoke("DeletarInstrumento", new object[] {
                        instrumento});
        }
        
        /// <remarks/>
        public void DeletarInstrumentoAsync(Instrumento instrumento) {
            this.DeletarInstrumentoAsync(instrumento, null);
        }
        
        /// <remarks/>
        public void DeletarInstrumentoAsync(Instrumento instrumento, object userState) {
            if ((this.DeletarInstrumentoOperationCompleted == null)) {
                this.DeletarInstrumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarInstrumentoOperationCompleted);
            }
            this.InvokeAsync("DeletarInstrumento", new object[] {
                        instrumento}, this.DeletarInstrumentoOperationCompleted, userState);
        }
        
        private void OnDeletarInstrumentoOperationCompleted(object arg) {
            if ((this.DeletarInstrumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarInstrumentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarInstrumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarInstrumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Instrumento instrumento) {
            this.Invoke("AlterarInstrumento", new object[] {
                        instrumento});
        }
        
        /// <remarks/>
        public void AlterarInstrumentoAsync(Instrumento instrumento) {
            this.AlterarInstrumentoAsync(instrumento, null);
        }
        
        /// <remarks/>
        public void AlterarInstrumentoAsync(Instrumento instrumento, object userState) {
            if ((this.AlterarInstrumentoOperationCompleted == null)) {
                this.AlterarInstrumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarInstrumentoOperationCompleted);
            }
            this.InvokeAsync("AlterarInstrumento", new object[] {
                        instrumento}, this.AlterarInstrumentoOperationCompleted, userState);
        }
        
        private void OnAlterarInstrumentoOperationCompleted(object arg) {
            if ((this.AlterarInstrumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarInstrumentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarInstrumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteInstrumento")]
        public Instrumento[] ListarInstrumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Instrumento filtro) {
            object[] results = this.Invoke("ListarInstrumento", new object[] {
                        filtro});
            return ((Instrumento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarInstrumentoAsync(Instrumento filtro) {
            this.ListarInstrumentoAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarInstrumentoAsync(Instrumento filtro, object userState) {
            if ((this.ListarInstrumentoOperationCompleted == null)) {
                this.ListarInstrumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarInstrumentoOperationCompleted);
            }
            this.InvokeAsync("ListarInstrumento", new object[] {
                        filtro}, this.ListarInstrumentoOperationCompleted, userState);
        }
        
        private void OnListarInstrumentoOperationCompleted(object arg) {
            if ((this.ListarInstrumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarInstrumentoCompleted(this, new ListarInstrumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirTipo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Tipo tipo) {
            this.Invoke("InserirTipo", new object[] {
                        tipo});
        }
        
        /// <remarks/>
        public void InserirTipoAsync(Tipo tipo) {
            this.InserirTipoAsync(tipo, null);
        }
        
        /// <remarks/>
        public void InserirTipoAsync(Tipo tipo, object userState) {
            if ((this.InserirTipoOperationCompleted == null)) {
                this.InserirTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirTipoOperationCompleted);
            }
            this.InvokeAsync("InserirTipo", new object[] {
                        tipo}, this.InserirTipoOperationCompleted, userState);
        }
        
        private void OnInserirTipoOperationCompleted(object arg) {
            if ((this.InserirTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirTipoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarTipo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Tipo tipo) {
            this.Invoke("DeletarTipo", new object[] {
                        tipo});
        }
        
        /// <remarks/>
        public void DeletarTipoAsync(Tipo tipo) {
            this.DeletarTipoAsync(tipo, null);
        }
        
        /// <remarks/>
        public void DeletarTipoAsync(Tipo tipo, object userState) {
            if ((this.DeletarTipoOperationCompleted == null)) {
                this.DeletarTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarTipoOperationCompleted);
            }
            this.InvokeAsync("DeletarTipo", new object[] {
                        tipo}, this.DeletarTipoOperationCompleted, userState);
        }
        
        private void OnDeletarTipoOperationCompleted(object arg) {
            if ((this.DeletarTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarTipoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarTipo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Tipo tipo) {
            this.Invoke("AlterarTipo", new object[] {
                        tipo});
        }
        
        /// <remarks/>
        public void AlterarTipoAsync(Tipo tipo) {
            this.AlterarTipoAsync(tipo, null);
        }
        
        /// <remarks/>
        public void AlterarTipoAsync(Tipo tipo, object userState) {
            if ((this.AlterarTipoOperationCompleted == null)) {
                this.AlterarTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarTipoOperationCompleted);
            }
            this.InvokeAsync("AlterarTipo", new object[] {
                        tipo}, this.AlterarTipoOperationCompleted, userState);
        }
        
        private void OnAlterarTipoOperationCompleted(object arg) {
            if ((this.AlterarTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarTipoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteTipo")]
        public Tipo[] ListarTipo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Tipo filtro) {
            object[] results = this.Invoke("ListarTipo", new object[] {
                        filtro});
            return ((Tipo[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTipoAsync(Tipo filtro) {
            this.ListarTipoAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarTipoAsync(Tipo filtro, object userState) {
            if ((this.ListarTipoOperationCompleted == null)) {
                this.ListarTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTipoOperationCompleted);
            }
            this.InvokeAsync("ListarTipo", new object[] {
                        filtro}, this.ListarTipoOperationCompleted, userState);
        }
        
        private void OnListarTipoOperationCompleted(object arg) {
            if ((this.ListarTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTipoCompleted(this, new ListarTipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirLocacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirLocacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Locacao locacao) {
            this.Invoke("InserirLocacao", new object[] {
                        locacao});
        }
        
        /// <remarks/>
        public void InserirLocacaoAsync(Locacao locacao) {
            this.InserirLocacaoAsync(locacao, null);
        }
        
        /// <remarks/>
        public void InserirLocacaoAsync(Locacao locacao, object userState) {
            if ((this.InserirLocacaoOperationCompleted == null)) {
                this.InserirLocacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirLocacaoOperationCompleted);
            }
            this.InvokeAsync("InserirLocacao", new object[] {
                        locacao}, this.InserirLocacaoOperationCompleted, userState);
        }
        
        private void OnInserirLocacaoOperationCompleted(object arg) {
            if ((this.InserirLocacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirLocacaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CancelarLocacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelarLocacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Locacao locacao) {
            this.Invoke("CancelarLocacao", new object[] {
                        locacao});
        }
        
        /// <remarks/>
        public void CancelarLocacaoAsync(Locacao locacao) {
            this.CancelarLocacaoAsync(locacao, null);
        }
        
        /// <remarks/>
        public void CancelarLocacaoAsync(Locacao locacao, object userState) {
            if ((this.CancelarLocacaoOperationCompleted == null)) {
                this.CancelarLocacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarLocacaoOperationCompleted);
            }
            this.InvokeAsync("CancelarLocacao", new object[] {
                        locacao}, this.CancelarLocacaoOperationCompleted, userState);
        }
        
        private void OnCancelarLocacaoOperationCompleted(object arg) {
            if ((this.CancelarLocacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarLocacaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarLocacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarLocacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Locacao locacao) {
            this.Invoke("AlterarLocacao", new object[] {
                        locacao});
        }
        
        /// <remarks/>
        public void AlterarLocacaoAsync(Locacao locacao) {
            this.AlterarLocacaoAsync(locacao, null);
        }
        
        /// <remarks/>
        public void AlterarLocacaoAsync(Locacao locacao, object userState) {
            if ((this.AlterarLocacaoOperationCompleted == null)) {
                this.AlterarLocacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarLocacaoOperationCompleted);
            }
            this.InvokeAsync("AlterarLocacao", new object[] {
                        locacao}, this.AlterarLocacaoOperationCompleted, userState);
        }
        
        private void OnAlterarLocacaoOperationCompleted(object arg) {
            if ((this.AlterarLocacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarLocacaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarLocacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteLocacao")]
        public Locacao[] ListarLocacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Locacao filtro) {
            object[] results = this.Invoke("ListarLocacao", new object[] {
                        filtro});
            return ((Locacao[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarLocacaoAsync(Locacao filtro) {
            this.ListarLocacaoAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarLocacaoAsync(Locacao filtro, object userState) {
            if ((this.ListarLocacaoOperationCompleted == null)) {
                this.ListarLocacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarLocacaoOperationCompleted);
            }
            this.InvokeAsync("ListarLocacao", new object[] {
                        filtro}, this.ListarLocacaoOperationCompleted, userState);
        }
        
        private void OnListarLocacaoOperationCompleted(object arg) {
            if ((this.ListarLocacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarLocacaoCompleted(this, new ListarLocacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteCliente")]
    public partial class Cliente {
        
        private int clienteIDField;
        
        private string clienteNomeField;
        
        private string emailField;
        
        private string telefoneField;
        
        /// <remarks/>
        public int ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClienteNome {
            get {
                return this.clienteNomeField;
            }
            set {
                this.clienteNomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteLocacao")]
    public partial class Locacao {
        
        private Cliente clienteIDField;
        
        private string dataCancelamentoField;
        
        private string dataPagamentoField;
        
        private string dataVencimentoField;
        
        private int locacaoIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataCancelamento {
            get {
                return this.dataCancelamentoField;
            }
            set {
                this.dataCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataPagamento {
            get {
                return this.dataPagamentoField;
            }
            set {
                this.dataPagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataVencimento {
            get {
                return this.dataVencimentoField;
            }
            set {
                this.dataVencimentoField = value;
            }
        }
        
        /// <remarks/>
        public int LocacaoID {
            get {
                return this.locacaoIDField;
            }
            set {
                this.locacaoIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteTipo")]
    public partial class Tipo {
        
        private string nomeField;
        
        private int tipoIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int TipoID {
            get {
                return this.tipoIDField;
            }
            set {
                this.tipoIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteInstrumento")]
    public partial class Instrumento {
        
        private int instrumentoIDField;
        
        private string nomeField;
        
        private int tipoIDField;
        
        private double valorField;
        
        /// <remarks/>
        public int InstrumentoID {
            get {
                return this.instrumentoIDField;
            }
            set {
                this.instrumentoIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int TipoID {
            get {
                return this.tipoIDField;
            }
            set {
                this.tipoIDField = value;
            }
        }
        
        /// <remarks/>
        public double Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteHorario")]
    public partial class Horario {
        
        private string horarioFinalField;
        
        private int horarioIDField;
        
        private string horarioInicialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HorarioFinal {
            get {
                return this.horarioFinalField;
            }
            set {
                this.horarioFinalField = value;
            }
        }
        
        /// <remarks/>
        public int HorarioID {
            get {
                return this.horarioIDField;
            }
            set {
                this.horarioIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HorarioInicial {
            get {
                return this.horarioInicialField;
            }
            set {
                this.horarioInicialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteSala")]
    public partial class Sala {
        
        private string descricaoField;
        
        private int salaIDField;
        
        private string salaNomeField;
        
        private double valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int SalaID {
            get {
                return this.salaIDField;
            }
            set {
                this.salaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SalaNome {
            get {
                return this.salaNomeField;
            }
            set {
                this.salaNomeField = value;
            }
        }
        
        /// <remarks/>
        public double Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.pacoteArtista")]
    public partial class Artista {
        
        private int artistaIDField;
        
        private string emailField;
        
        private string nomeField;
        
        private string telefoneField;
        
        /// <remarks/>
        public int ArtistaID {
            get {
                return this.artistaIDField;
            }
            set {
                this.artistaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InserirClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeletarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AlterarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListarClienteCompletedEventHandler(object sender, ListarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InserirArtistaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeletarArtistaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AlterarArtistaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListarArtistaCompletedEventHandler(object sender, ListarArtistaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarArtistaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarArtistaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Artista[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Artista[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InserirSalaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeletarSalaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AlterarSalaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListarSalaCompletedEventHandler(object sender, ListarSalaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSalaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSalaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sala[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sala[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InserirHorarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeletarHorarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AlterarHorarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListarHorarioCompletedEventHandler(object sender, ListarHorarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarHorarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarHorarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Horario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Horario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InserirInstrumentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeletarInstrumentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AlterarInstrumentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListarInstrumentoCompletedEventHandler(object sender, ListarInstrumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarInstrumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarInstrumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Instrumento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Instrumento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InserirTipoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeletarTipoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AlterarTipoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListarTipoCompletedEventHandler(object sender, ListarTipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tipo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tipo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InserirLocacaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CancelarLocacaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AlterarLocacaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ListarLocacaoCompletedEventHandler(object sender, ListarLocacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarLocacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarLocacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Locacao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Locacao[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591